# Generated by Django 2.2.1 on 2019-05-24 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 7, 53, 24, 942479)),
        ),
    ]
